### ISSUE TITLE
Отрисовка стакана и фигур внутри него

### ISSUE THREAD

**Issue by stden** [levelp/QtTetris#2]
Фигур всего 7: I, J, L, O, S, T, Z. Можно сделать отдельный класс: Tetrimino или Figure. https://en.wikipedia.org/wiki/Tetris

**Comment by Taison4eg** [comment]
Коллеги, для отрисовки стакана и создания анимации (движения фигурок), предлагаю использовать средства SFML... Как подключить можно посмотреть на ютубе

**Comment by stden** [comment]
SFML можно скачать http://www.sfml-dev.org/download.php  Но можно пока ограничиться стандартными Qt Widgets.

**Comment by Taison4eg** [comment]
В принципе есть идея создать объект, который будет хранить  в себе поля : название фигурки, матрицу 4Х4 (для вырисовки объекта) , и текущие координаты (через них будем управлять движением и падением). Но какими средствами лучше рисовать на форме пока не ясно ... Может использовать переопределение функции базового класса widget ( что то связанное с paintEvent, но точно не помню как называется) ?

**Comment by stden** [comment]
e0765574f4594c6ecd2b57b5dd10edc0a2ace102 Рисуем стакан с помощью QPainter
