### ISSUE TITLE
Движение фигуры вниз по таймеру

### ISSUE THREAD

**Issue by stden** [levelp/QtTetris#3]
``` cpp
  QTimer* timer = new QTimer(this);
  // Соединяем сигнал со слотом
  connect(timer,
          SIGNAL(timeout()),
          this,
          SLOT(gameStep()));
  timer->start(1000);
```

**Comment by Taison4eg** [comment]
Почему то не удается переопределить стандартное событие keyPressEvent , при нажатии кнопки не попадаю в переопределенный метод, данное переопределение делаю в главной форме (установка фокуса setFocusPolicy ничего не дала ) .. Буду признателен, если вы подскажите что  делаю не так.

**Comment by Taison4eg** [comment]
Вопрос снят, ошибка была банальной (не правильный регистр в названии события).

**Comment by Taison4eg** [comment]
Реализовал в принципе движение вниз, и в стороны...
Нужно делать обработку столкновения с др объектами и тогда уже выкину первую  версию игры

**Comment by stden** [comment]
Отлично! Можете выкладывать промежуточные результаты!

**Comment by stden** [comment]
51a99524c7c0f75e652510360c39cae5381eda54 Движение фигуры вниз, реакция на кнопки Вправо - Влево
